import type { StaffMember } from "@/types/staff";
import type { Course } from "@/types/course";
import type { NewsArticle } from "@/types/news";
import type { Publication } from "@/types/publication";
import type { CalendarEvent } from "@/types/event";
import type { ResearchGroup } from "@/types/research";

// ── Staff (Real SU CS Division staff — sourced from cs.sun.ac.za) ──────────
export const mockStaff: StaffMember[] = [
  {
    id: "1",
    slug: "brink-van-der-merwe",
    name: "Prof. Brink van der Merwe",
    position: "Head of Division & Professor",
    bio: "Professor Brink van der Merwe leads the Computer Science Division and conducts research in tree automata and grammar learning. He holds a PhD from Stellenbosch University and has published extensively in theoretical computer science and formal language theory.",
    email: "abvdm@cs.sun.ac.za",
    imageUrl: null,
    researchAreas: ["Tree Automata", "Grammar Learning", "Formal Language Theory"],
    officeLocation: "Mathematical Sciences Building, Room 1006",
  },
  {
    id: "2",
    slug: "andries-engelbrecht",
    name: "Prof. Andries Engelbrecht",
    position: "Professor",
    bio: "Professor Andries Engelbrecht is an internationally recognised expert in computational intelligence. His research spans swarm intelligence, evolutionary computation, machine learning, and neural network optimisation. He is the author of two widely used textbooks in computational intelligence.",
    email: "engel@sun.ac.za",
    imageUrl: null,
    researchAreas: ["Swarm Intelligence", "Evolutionary Computation", "Machine Learning", "Optimisation"],
    officeLocation: "Mathematical Sciences Building, Room 1010",
  },
  {
    id: "3",
    slug: "bernd-fischer",
    name: "Prof. Bernd Fischer",
    position: "Professor",
    bio: "Professor Bernd Fischer's research lies at the intersection of software engineering, formal methods, and artificial intelligence. He works on program verification, automated reasoning, and the application of AI techniques to software analysis.",
    email: "bfischer@cs.sun.ac.za",
    imageUrl: null,
    researchAreas: ["Software Engineering", "Formal Methods", "Program Verification", "AI"],
    officeLocation: "Mathematical Sciences Building, Room 1014",
  },
  {
    id: "4",
    slug: "william-tucker",
    name: "Prof. William Tucker",
    position: "Professor",
    bio: "Professor William Tucker's research interests include computer networks, human-computer interaction, and ethical computing. He is involved in projects examining the social impact of technology in African communities and is a champion for responsible computing.",
    email: "btucker@sun.ac.za",
    imageUrl: null,
    researchAreas: ["Computer Networks", "Human-Computer Interaction", "Ethical Computing"],
    officeLocation: "Mathematical Sciences Building, Room 1016",
  },
  {
    id: "5",
    slug: "lynette-van-zijl",
    name: "Prof. Lynette van Zijl",
    position: "Professor",
    bio: "Professor Lynette van Zijl conducts research in automata implementation and assistive technologies. Her work bridges theoretical computer science with practical applications that improve accessibility for people with disabilities.",
    email: "lvzijl@sun.ac.za",
    imageUrl: null,
    researchAreas: ["Automata Implementation", "Assistive Technologies", "Formal Languages"],
    officeLocation: "Mathematical Sciences Building, Room 1018",
  },
  {
    id: "6",
    slug: "steve-kroon",
    name: "Assoc. Prof. Steve Kroon",
    position: "Associate Professor",
    bio: "Associate Professor Steve Kroon's research focuses on artificial intelligence, machine learning, and statistical learning theory. He works on PAC learning, probabilistic models, and the theoretical foundations of modern machine learning algorithms.",
    email: "kroon@sun.ac.za",
    imageUrl: null,
    researchAreas: ["Artificial Intelligence", "Machine Learning", "Statistical Learning Theory"],
    officeLocation: "Mathematical Sciences Building, Room 1020",
  },
  {
    id: "7",
    slug: "cornelia-inggs",
    name: "Dr. Cornelia Inggs",
    position: "Senior Lecturer",
    bio: "Dr. Cornelia Inggs specialises in formal methods, model checking, and concurrency theory. She supervises postgraduate students working on verification of concurrent and distributed systems, with a focus on software correctness.",
    email: "cinggs@cs.sun.ac.za",
    imageUrl: null,
    researchAreas: ["Formal Methods", "Model Checking", "Concurrency"],
    officeLocation: "Mathematical Sciences Building, Room 1024",
  },
  {
    id: "8",
    slug: "marcel-dunaiski",
    name: "Dr. Marcel Dunaiski",
    position: "Senior Lecturer",
    bio: "Dr. Marcel Dunaiski's research interests lie in data science, informetrics, and scientometrics. He develops computational methods to analyse scholarly communication patterns, citation networks, and research impact metrics.",
    email: "marceldunaiski@sun.ac.za",
    imageUrl: null,
    researchAreas: ["Data Science", "Informetrics", "Scientometrics"],
    officeLocation: "Mathematical Sciences Building, Room 1026",
  },
  {
    id: "9",
    slug: "willem-visser",
    name: "Prof. Willem Visser",
    position: "Part-time Professor",
    bio: "Professor Willem Visser is an internationally recognised researcher in software engineering, automated testing, and symbolic execution. He previously worked at NASA Ames Research Center and is the co-creator of the Java PathFinder model checker.",
    email: "visserw@sun.ac.za",
    imageUrl: null,
    researchAreas: ["Software Engineering", "Automated Testing", "Symbolic Execution"],
    googleScholarUrl: "https://scholar.google.com/citations?user=WvisserSU",
    officeLocation: "Mathematical Sciences Building",
  },
  {
    id: "10",
    slug: "trienko-grobler",
    name: "Dr. Trienko Grobler",
    position: "Lecturer",
    bio: "Dr. Trienko Grobler's research focuses on machine learning, remote sensing, and coding theory. He develops deep learning methods for satellite image analysis and applies information-theoretic approaches to data compression and classification.",
    email: "tlgrobler@sun.ac.za",
    imageUrl: null,
    researchAreas: ["Machine Learning", "Remote Sensing", "Coding Theory"],
    officeLocation: "Mathematical Sciences Building, Room 1030",
  },
  {
    id: "11",
    slug: "mkhuseli-ngxande",
    name: "Mr. Mkhuseli Ngxande",
    position: "Lecturer",
    bio: "Mr. Mkhuseli Ngxande's research interests include machine learning, computer vision, and bioinformatics. He is passionate about applying AI methods to pressing healthcare and biological challenges facing the African continent.",
    email: "ngxandem@sun.ac.za",
    imageUrl: null,
    researchAreas: ["Machine Learning", "Computer Vision", "Bioinformatics"],
    officeLocation: "Mathematical Sciences Building, Room 1032",
  },
  {
    id: "12",
    slug: "gavin-rens",
    name: "Dr. Gavin Rens",
    position: "Lecturer",
    bio: "Dr. Gavin Rens works on cognitive robotics, knowledge representation, and reinforcement learning. His research develops formal frameworks for autonomous agents that must reason under uncertainty and act rationally in dynamic environments.",
    email: "gavinrens@sun.ac.za",
    imageUrl: null,
    researchAreas: ["Cognitive Robotics", "Knowledge Representation", "Reinforcement Learning"],
    officeLocation: "Mathematical Sciences Building, Room 1034",
  },
  {
    id: "13",
    slug: "willem-bester",
    name: "Mr. Willem Bester",
    position: "Junior Lecturer",
    bio: "Mr. Willem Bester teaches software engineering and formal methods at the undergraduate level. His academic interests include formal language theory, automata, and the application of rigorous mathematical methods to software design.",
    email: "whkbester@cs.sun.ac.za",
    imageUrl: null,
    researchAreas: ["Software Engineering", "Formal Methods", "Formal Language Theory"],
    officeLocation: "Mathematical Sciences Building, Room 1038",
  },
];

// ── Research Groups ────────────────────────────────────────────────────────
export const mockResearchGroups: ResearchGroup[] = [
  {
    id: "1",
    slug: "ai-ml-lab",
    name: "Artificial Intelligence & Machine Learning",
    shortName: "AI-ML Lab",
    description:
      "The AI-ML group investigates foundational and applied machine learning, with a focus on swarm intelligence, evolutionary algorithms, deep learning, and statistical learning theory. The group collaborates with industry partners across Africa and internationally.",
    focus: ["Deep Learning", "Swarm Intelligence", "Evolutionary Computation", "Statistical Learning"],
    leaderId: "2",
    leaderName: "Prof. Andries Engelbrecht",
    memberCount: 14,
    imageUrl: null,
    websiteUrl: "https://www.cs.sun.ac.za/research",
  },
  {
    id: "2",
    slug: "formal-methods-verification",
    name: "Formal Methods & Verification",
    shortName: "FMV Group",
    description:
      "The FMV group advances formal language theory, model checking, automata implementation, and program verification. Research outputs include theoretical contributions and open-source verification tools used by the global software engineering community.",
    focus: ["Formal Languages", "Model Checking", "Automata Theory", "Program Verification"],
    leaderId: "1",
    leaderName: "Prof. Brink van der Merwe",
    memberCount: 9,
    imageUrl: null,
    websiteUrl: "https://www.cs.sun.ac.za/research",
  },
  {
    id: "3",
    slug: "software-engineering",
    name: "Software Engineering & Testing",
    shortName: "SET Group",
    description:
      "The SET group works on software testing, symbolic execution, automated reasoning, and the application of AI to software analysis. Led by internationally recognised researchers with experience at NASA and major technology companies.",
    focus: ["Symbolic Execution", "Automated Testing", "AI for Software", "Program Analysis"],
    leaderId: "3",
    leaderName: "Prof. Bernd Fischer",
    memberCount: 8,
    imageUrl: null,
    websiteUrl: "https://www.cs.sun.ac.za/research",
  },
  {
    id: "4",
    slug: "computer-vision-robotics",
    name: "Computer Vision & Robotics",
    shortName: "CVR Lab",
    description:
      "The CVR Lab conducts research in computer vision, cognitive robotics, remote sensing, and bioinformatics. Current projects include satellite image classification using deep learning and autonomous agent reasoning under uncertainty.",
    focus: ["Computer Vision", "Cognitive Robotics", "Remote Sensing", "Bioinformatics"],
    leaderId: "6",
    leaderName: "Assoc. Prof. Steve Kroon",
    memberCount: 10,
    imageUrl: null,
    websiteUrl: "https://www.cs.sun.ac.za/research",
  },
];

// ── Courses ────────────────────────────────────────────────────────────────
export const mockCourses: Course[] = [
  // Year 1
  { id: "c1", code: "CS114", title: "Introduction to Programming", description: "Foundational programming concepts using Python. Topics include variables, control flow, functions, and basic data structures. Emphasis on problem-solving and algorithmic thinking.", credits: 16, yearLevel: 1, level: "undergraduate", semester: "first" },
  { id: "c2", code: "CS144", title: "Discrete Mathematics for CS", description: "Logic, sets, relations, functions, graph theory, and combinatorics as applied to computer science. Formal proof techniques and mathematical reasoning.", credits: 16, yearLevel: 1, level: "undergraduate", semester: "first" },
  { id: "c3", code: "CS154", title: "Data Structures & Algorithms", description: "Fundamental data structures (lists, trees, graphs, hash tables) and algorithm analysis. Sorting, searching, and design strategies including divide-and-conquer and dynamic programming.", credits: 16, yearLevel: 1, level: "undergraduate", semester: "second" },
  { id: "c4", code: "CS164", title: "Computer Organisation", description: "Digital logic, machine architecture, assembly language, memory systems, and the hardware-software interface. Practical labs using RISC-V assembly.", credits: 16, yearLevel: 1, level: "undergraduate", semester: "second" },
  // Year 2
  { id: "c5", code: "CS214", title: "Algorithms & Complexity", description: "Advanced algorithm design: divide-and-conquer, dynamic programming, greedy algorithms, graph algorithms, and complexity theory (P vs NP). Amortised analysis.", credits: 16, yearLevel: 2, level: "undergraduate", semester: "first", prerequisites: ["CS154"] },
  { id: "c6", code: "CS244", title: "Object-Oriented Design", description: "Design patterns, UML modelling, SOLID principles, and software architecture using Java. Emphasis on maintainability, testability, and team collaboration.", credits: 16, yearLevel: 2, level: "undergraduate", semester: "first", prerequisites: ["CS114"] },
  { id: "c7", code: "CS254", title: "Operating Systems", description: "Processes, threads, scheduling, memory management, file systems, and concurrency in modern operating systems. Practical labs in C.", credits: 16, yearLevel: 2, level: "undergraduate", semester: "second", prerequisites: ["CS164"] },
  { id: "c8", code: "CS264", title: "Databases & Information Systems", description: "Relational model, SQL, normalisation, query optimisation, transactions, and NoSQL databases. Practical project using PostgreSQL.", credits: 16, yearLevel: 2, level: "undergraduate", semester: "second", prerequisites: ["CS154"] },
  // Year 3
  { id: "c9", code: "CS314", title: "Machine Learning", description: "Supervised and unsupervised learning, neural networks, model evaluation, regularisation, and ethical AI. Practical labs in Python using PyTorch.", credits: 16, yearLevel: 3, level: "undergraduate", semester: "first", prerequisites: ["CS214", "CS264"] },
  { id: "c10", code: "CS344", title: "Software Engineering", description: "Agile methodologies, requirements engineering, software testing, CI/CD, and team-based development. Capstone group project with industry mentor.", credits: 16, yearLevel: 3, level: "undergraduate", semester: "first", prerequisites: ["CS244"] },
  { id: "c11", code: "CS354", title: "Computer Networks", description: "Network protocols, TCP/IP stack, socket programming, network security, wireless networking, and cloud architectures.", credits: 16, yearLevel: 3, level: "undergraduate", semester: "second", prerequisites: ["CS254"] },
  { id: "c12", code: "CS364", title: "Formal Languages & Automata", description: "Finite automata, regular expressions, context-free grammars, pushdown automata, Turing machines, and decidability. Theoretical foundations of computation.", credits: 16, yearLevel: 3, level: "undergraduate", semester: "second", prerequisites: ["CS144"] },
  // Postgraduate
  { id: "c13", code: "CS871", title: "Advanced Machine Learning", description: "Deep learning theory, transformers, diffusion models, reinforcement learning, and research frontiers in AI. Reading and presentation of recent papers.", credits: 20, yearLevel: 4, level: "postgraduate", semester: "first", prerequisites: ["CS314"] },
  { id: "c14", code: "CS872", title: "Formal Methods & Verification", description: "Temporal logic, model checkers (SPIN, NuSMV), theorem provers, and their application to safety-critical system verification.", credits: 20, yearLevel: 4, level: "postgraduate", semester: "first" },
  { id: "c15", code: "CS873", title: "Swarm Intelligence & Evolutionary Computation", description: "Particle swarm optimisation, ant colony optimisation, genetic algorithms, differential evolution, and applications to complex optimisation problems.", credits: 20, yearLevel: 4, level: "postgraduate", semester: "second" },
  { id: "c16", code: "CS874", title: "Research Methodology", description: "Scientific writing, literature review, experimental design, statistical analysis, and ethics in computing research. Mandatory for all Honours students.", credits: 20, yearLevel: 4, level: "postgraduate", semester: "year" },
];

// ── News ───────────────────────────────────────────────────────────────────
export const mockNews: NewsArticle[] = [
  {
    id: "n1",
    slug: "cs-team-wins-icpc-2025",
    title: "SU CS Team Claims Gold at ICPC African Regional Championship",
    excerpt: "Three undergraduate students representing Stellenbosch University brought home top honours at the 2025 ICPC African Regional Programming Contest held in Nairobi.",
    body: "<p>Three undergraduate students representing Stellenbosch University brought home top honours at the 2025 ICPC African Regional Programming Contest held in Nairobi. The team solved all 12 problems within the time limit, placing first among 47 competing teams from across the continent.</p><p>Team captain Lara Smit commented: 'The problems this year were exceptionally challenging, particularly the graph optimisation set. We are proud to represent SU.'</p>",
    imageUrl: null,
    category: "Awards",
    publishedAt: "2025-11-12T09:00:00Z",
    author: "CS Communications",
  },
  {
    id: "n2",
    slug: "new-ai-research-grant",
    title: "Division Secures R8M NRF Grant for Responsible AI Research",
    excerpt: "The National Research Foundation has awarded the AI-ML group a three-year grant to investigate fairness, accountability, and transparency in machine learning systems deployed in public services.",
    body: "<p>The National Research Foundation has awarded the AI-ML group a three-year grant to investigate fairness, accountability, and transparency in machine learning systems deployed in public services.</p><p>The grant will fund three doctoral students and two postdoctoral researchers, as well as establish a new Responsible AI Centre in the Mathematical Sciences building.</p>",
    imageUrl: null,
    category: "Research",
    publishedAt: "2025-10-28T08:00:00Z",
    author: "Prof. Andries Engelbrecht",
  },
  {
    id: "n3",
    slug: "devcs-hackathon-2026",
    title: "DevCS Hackathon 2026: Register Now for 48-Hour Innovation Sprint",
    excerpt: "The annual DevCS Hackathon returns in February 2026. Students from all South African universities are invited to compete for prizes worth over R100,000.",
    body: "<p>The annual DevCS Hackathon returns in February 2026. Students from all South African universities are invited to compete for prizes worth over R100,000 across six challenge tracks including health-tech, fintech, and climate solutions.</p>",
    imageUrl: null,
    category: "Events",
    publishedAt: "2025-10-01T10:00:00Z",
    author: "Student Affairs",
  },
  {
    id: "n4",
    slug: "professor-visser-award",
    title: "Prof. Willem Visser Elected ACM Distinguished Member",
    excerpt: "Professor Willem Visser has been elected as an ACM Distinguished Member for outstanding contributions to software model checking and automated program analysis.",
    body: "<p>Professor Willem Visser has been elected as an ACM Distinguished Member for outstanding contributions to software model checking and automated program analysis. The ACM recognised his seminal work on the Java PathFinder verification tool, which has been used worldwide in academia and industry.</p>",
    imageUrl: null,
    category: "Awards",
    publishedAt: "2025-09-15T07:00:00Z",
    author: "CS Communications",
  },
  {
    id: "n5",
    slug: "engelbrecht-textbook-4th-ed",
    title: "Prof. Engelbrecht Releases Fourth Edition of Computational Intelligence Textbook",
    excerpt: "The fourth edition of 'Computational Intelligence: An Introduction' by Prof. Andries Engelbrecht has been published, featuring new chapters on deep reinforcement learning and neuroevolution.",
    body: "<p>The fourth edition of 'Computational Intelligence: An Introduction' by Prof. Andries Engelbrecht has been published by Wiley, featuring new chapters on deep reinforcement learning and neuroevolution. The textbook is used in universities across 40 countries.</p>",
    imageUrl: null,
    category: "Research",
    publishedAt: "2025-08-20T09:30:00Z",
    author: "CS Communications",
  },
];

// ── Events ─────────────────────────────────────────────────────────────────
export const mockEvents: CalendarEvent[] = [
  {
    id: "e1",
    title: "Weekly CS Colloquium: Graph Neural Networks for Drug Discovery",
    description: "Dr. Sarah Chen from UCT presents her work on using GNNs to accelerate pharmaceutical research. Tea and coffee from 12:45.",
    startDate: "2026-03-06T13:00:00Z",
    endDate: "2026-03-06T14:00:00Z",
    location: "Mathematical Sciences Building, Seminar Room A",
    type: "seminar",
    speaker: "Dr. Sarah Chen (UCT)",
    isOnline: false,
  },
  {
    id: "e2",
    title: "Honours Project Showcase 2026",
    description: "Final-year Honours students present their research projects to academic staff, industry partners, and fellow students.",
    startDate: "2026-03-20T09:00:00Z",
    endDate: "2026-03-20T17:00:00Z",
    location: "Engineering A Block, Great Hall",
    type: "other",
    isOnline: false,
    registrationUrl: "#",
  },
  {
    id: "e3",
    title: "Workshop: Introduction to Rust for Systems Programming",
    description: "A hands-on two-day workshop covering Rust fundamentals, ownership, and building safe concurrent applications. Laptops required.",
    startDate: "2026-04-02T09:00:00Z",
    endDate: "2026-04-03T17:00:00Z",
    location: "Mathematical Sciences, Computer Lab 2",
    type: "workshop",
    isOnline: false,
    registrationUrl: "#",
  },
  {
    id: "e4",
    title: "Industry Panel: Careers in AI & Data Science",
    description: "Representatives from major South African tech companies discuss career paths, skills required, and the state of the local AI industry.",
    startDate: "2026-04-15T14:00:00Z",
    endDate: "2026-04-15T16:00:00Z",
    location: "Online (Zoom)",
    type: "seminar",
    isOnline: true,
    registrationUrl: "#",
  },
  {
    id: "e5",
    title: "Postgraduate Application Deadline — 2027 Entry",
    description: "Last day to submit applications for Honours, Masters, and PhD programmes commencing in January 2027.",
    startDate: "2026-09-30T23:59:00Z",
    endDate: "2026-09-30T23:59:00Z",
    location: "Online",
    type: "deadline",
    isOnline: true,
  },
];

// ── Publications ───────────────────────────────────────────────────────────
export const mockPublications: Publication[] = [
  {
    id: "p1",
    title: "Transformer-Based Sequence Models for Low-Resource African Languages",
    authors: ["A. Engelbrecht", "T. Molefe", "S. Nkosi"],
    abstract: "We present a novel pre-training strategy for transformer models on extremely low-resource Bantu languages, achieving state-of-the-art results on four benchmark tasks with less than 1M training tokens.",
    year: 2025,
    doi: "10.18653/v1/2025.acl-main.123",
    venue: "Proceedings of ACL 2025",
    type: "conference",
  },
  {
    id: "p2",
    title: "Symbolic Execution of Concurrent Programs via Thread-Modular Analysis",
    authors: ["W. Visser", "B. Fischer", "M. Botha"],
    abstract: "We present a thread-modular symbolic execution framework that scales to realistic concurrent Java programs, uncovering data races and deadlocks missed by existing tools.",
    year: 2025,
    doi: "10.1145/3607729.3608000",
    venue: "ICSE 2025",
    type: "conference",
  },
  {
    id: "p3",
    title: "Tree Automata Minimisation via Partition Refinement",
    authors: ["B. van der Merwe", "L. van Zijl"],
    abstract: "We develop an efficient partition-refinement algorithm for minimising deterministic top-down tree automata, achieving O(n log n) time complexity and significantly reducing state space in practice.",
    year: 2024,
    doi: "10.1016/j.tcs.2024.114432",
    venue: "Theoretical Computer Science",
    type: "journal",
  },
  {
    id: "p4",
    title: "Swarm Intelligence for Multi-Objective Optimisation in Smart Grids",
    authors: ["A. Engelbrecht", "K. Louw"],
    abstract: "We apply particle swarm optimisation to multi-objective load balancing in smart grids, demonstrating 28% reduction in peak-hour energy costs compared to conventional scheduling algorithms.",
    year: 2024,
    doi: "10.1109/TPWRS.2024.10610000",
    venue: "IEEE Transactions on Power Systems",
    type: "journal",
  },
  {
    id: "p5",
    title: "Cognitive Robot Architecture for Belief-Desire-Intention Planning",
    authors: ["G. Rens", "S. Kroon"],
    abstract: "A new probabilistic BDI architecture is presented for autonomous robots operating in partially observable environments, with formal guarantees on rational action selection.",
    year: 2024,
    doi: "10.1145/3620678.3624690",
    venue: "AAMAS 2024",
    type: "conference",
  },
  {
    id: "p6",
    title: "Computational Intelligence: An Introduction (4th Edition)",
    authors: ["A. Engelbrecht"],
    abstract: "Comprehensive reference covering swarm intelligence, evolutionary computation, neural networks, and deep reinforcement learning, with new chapters on neuroevolution and AI ethics.",
    year: 2025,
    venue: "Wiley",
    type: "book",
  },
];
